keys:
  - &admin_ivan770 ba77c0b64e91ecd7523642bb5705d5d0b62a3b0a
  - &server_cobalt age1rqunush2hefaymv0gp8qy6dlph9a7lk33u62la0sqe24aprzw4kqyrtkjq
creation_rules:
  - path_regex: ^secrets.yaml$
    key_groups:
    - pgp:
      - *admin_ivan770
      age:
      - *server_cobalt
